### ISSUE TITLE
Roadmap to v 1.1

### ISSUE THREAD

**Issue by ahopkins** [ahopkins/sanic-jwt#88]
[] Add hooks and helper methods - #67, #70, #71 
[] Move decorators to `Initialize` instance - #68 
[] Configuration getters - #72 
[x] Optional user instance in `extend_payload` - #81 
[] Cleanup and remove deprecated code - #84 
[] Refactor "confusing" methods, eg `is_authenticated` - #86 
[] User injection into protected routes - #87

**Comment by vltr** [comment]
Allright, let me see if I can sum up everything I've done in the `into-1.1` branch:

- [x] Check consistency of all initialization classes on `Initialization` (issue #92) - 
30ce0fc
- [x] Minor improvement to the documentation (issue #91), but this needs some more attention - 3bf1e7821e7e9a4f27499152c13096a21bb7cc82
- [x] Implemented decorators to the `Initialize` instance (issue #68), without breaking backwards compatibility - 3bf1e7821e7e9a4f27499152c13096a21bb7cc82
- [x] Cleanup old or unecessary code, also reorganizing some calls a little bit (issue #84) - 3bf1e7821e7e9a4f27499152c13096a21bb7cc82 484bc4b87ce0857b98559378aabbfe6a0c8ecf3d 6e0e3a3220bf18705c1a42e354a900ec15e71a83 c95f9674d1bc061c80584516662fb7aed63f4b61
- [x] Add the option to generate your custom `refresh_token` inside `Configuration`, in case anyone wants to use CUIDs or any other string instead of a random string (no issue created) - 484bc4b87ce0857b98559378aabbfe6a0c8ecf3d
- [x] Implemented the new `Configuration` system with getters (issue #72) - 6e0e3a3220bf18705c1a42e354a900ec15e71a83 b31977d88318f43cdfc087516a44e1bb17434aee
- [x] Add a missing feature (if I can say so) that checks if the `authenticate` method, if not passed as parameter to `Initialize`, is not present in the `Authentication` class and if it is different from the `Authentication.authenticate` method, which allows developers to implement the method by just subclassing `Authentication` (no issue related) - 6e0e3a3220bf18705c1a42e354a900ec15e71a83
- [x] Upgraded pytest to a newer version so I can make usage of the `caplog` fixture (no issue related) - 888f57f9b98e311ac2e88812578c2237a17dd9a8 4d4249f1ed306521ecd703a93eb4283d491e97ab
- [x] Performed an audit to the code to provide a higher coverage - 95%+ :muscle: (no specific issue related) - bbabab8294949bed06c9b9805d3f4e2e1fca2e7a c95f9674d1bc061c80584516662fb7aed63f4b61
- [x] Fixed bug with `abort` inside custom decorators (issue #93) - f210a599cff0808b95d4569e3adc7b344a6b910b
- [x] Add `black` into the `Makefile` to provide code formatting and had to modify `pytest.ini` so warning `W503` gets ignored (issue #94) - f210a599cff0808b95d4569e3adc7b344a6b910b 71100228c31ca0b599078f959fdd24a2810be38e
- [x] Created a file called `requirements.in` inside `example` folder without any version related to this specific commit and created `requirements.txt` using [`pip-tools`](https://github.com/jazzband/pip-tools) (no issue related) - 4d4249f1ed306521ecd703a93eb4283d491e97ab
- [x] Implemented some decoupling regarding microservice architectures (issue #90) - c95f9674d1bc061c80584516662fb7aed63f4b61

**Comment by vltr** [comment]
- [x] Added possibility to override / implement your own endpoints (like `/auth`, `/auth/me` and etc) if necessary (edge cases I guess) (issue #97) - b07278077662777750a09e33754fa85503988be4
